export const hourFormat = [
  { value: 12, period: "AM" },
  { value: 1, period: "AM" },
  { value: 2, period: "AM" },
  { value: 3, period: "AM" },
  { value: 4, period: "AM" },
  { value: 5, period: "AM" },
  { value: 6, period: "AM" },
  { value: 7, period: "AM" },
  { value: 8, period: "AM" },
  { value: 9, period: "AM" },
  { value: 10, period: "AM" },
  { value: 11, period: "AM" },
  { value: 12, period: "PM" },
  { value: 1, period: "PM" },
  { value: 2, period: "PM" },
  { value: 3, period: "PM" },
  { value: 4, period: "PM" },
  { value: 5, period: "PM" },
  { value: 6, period: "PM" },
  { value: 7, period: "PM" },
  { value: 8, period: "PM" },
  { value: 9, period: "PM" },
  { value: 10, period: "PM" },
  { value: 11, period: "PM" },
];
export const daysOfWeek = [
  "Sunday",
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday",
];
export const YoutubeCategories = {
  1: "Film & Animation",
  2: " Autos & Vehicles",
  10: "Music",
  15: "Pets & Animals",
  17: "Sports",
  18: "Short Movies",
  19: "Travel & Events",
  20: "Gaming",
  21: "Videoblogging",
  22: "People & Blogs",
  23: "Comedy",
  24: "Entertainment",
  25: "News & Politics",
  26: " Howto & Style",
  27: "Education",
  28: " Science & Technology",
  29: " Nonprofits & Activism",
  30: "Movies",
  31: "Anime/Animation",
  32: "Action/Adventure",
  33: "Classics",
  34: "Comedy",
  35: "Documentary",
  36: "Drama",
  37: "Family",
  38: "Foreign",
  39: "Horror",
  40: "Sci:Fi/Fantasy",
  41: "Thriller",
  42: "Shorts",
  43: "Shows",
  44: "Trailers",
};
