export const hourFormat = [
  { value: 12, period: "AM" },
  { value: 1, period: "AM" },
  { value: 2, period: "AM" },
  { value: 3, period: "AM" },
  { value: 4, period: "AM" },
  { value: 5, period: "AM" },
  { value: 6, period: "AM" },
  { value: 7, period: "AM" },
  { value: 8, period: "AM" },
  { value: 9, period: "AM" },
  { value: 10, period: "AM" },
  { value: 11, period: "AM" },
  { value: 12, period: "PM" },
  { value: 1, period: "PM" },
  { value: 2, period: "PM" },
  { value: 3, period: "PM" },
  { value: 4, period: "PM" },
  { value: 5, period: "PM" },
  { value: 6, period: "PM" },
  { value: 7, period: "PM" },
  { value: 8, period: "PM" },
  { value: 9, period: "PM" },
  { value: 10, period: "PM" },
  { value: 11, period: "PM" },
];
